e-pustakshala-main/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('Cart/', views.CartView , name="CartView"),
    path('Cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('Cart/Remove/<int:id>', views.remove_from_cart , name="remove_from_cart"),
    path('Cart/Delete/<int:id>', views.decreaseCart , name="decreaseCart"),
    path('Cart/Checkout', views.Checkout , name="Checkout"),
    path('Cart/invoice', views.invoice , name="invoice"),
]

e-pustakshala-main/Pustakshala/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import smtplib

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Registration.urls')),
    path('', include('MainIndex.urls')),
    path('', include('Cart.urls')),

]
 
urlpatterns +=staticfiles_urlpatterns()

e-pustakshala-main/Registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = 'Registration'

urlpatterns = [
    # url(r'^login/$', auth_views.login, {'template_name': 'mysite/login_user.html'})
   path('Login', views.Login , name='Login'),
    path('Register', views.Register , name='Register'),
    path('LoggedIn',views.cust_login1,name="cust_login1"),
    path('LoggedOut', views.Logout, name="Logout"),
]

e-pustakshala-main/templates/LoginRegister/Login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'LoginRegister/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'LoginRegister/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form"  method="POST">
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="username" placeholder="UserName">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>
					{% comment %} <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="Email" name="email"  id="CustomerEmail" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div> {% endcomment %}
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					{% if form.non_field_errors %}
					<ul class='form-errors'>
						{% for error in form.non_field_errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-100">
						<a class="txt2" href="{% url 'Registration:Register' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'LoginRegister/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'LoginRegister/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/js/main.js' %}"></script>

</body>
</html>


{% comment %} <html>
	<body>
		<form method="POST">
			{% csrf_token %}
			{{ form }}
			<button Value="Submit" type="Submit">Submit</button>
		</form>
	</body>
</html> {% endcomment %}

e-pustakshala-main/templates/LoginRegister/Register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Regstration Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'LoginRegister/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'LoginRegister/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'LoginRegister/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST" action="{% url 'Registration:Register' %}">
				{% csrf_token %}
					<span class="login100-form-title">
						Member Registration
					</span>

						<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="text" name="username" id="CustomerName" placeholder="UserName">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="Email" name="email"  id="CustomerEmail" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password1"  id="CustomerPassword" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					{% comment %} <div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password2"  id="CustomerPassword2" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div> {% endcomment %}
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Register
						</button>
					</div>

					<div class="text-center p-t-50">
						<a class="txt2" href="{% url 'Registration:Login' %}">
							Login to your account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'LoginRegister/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'LoginRegister/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'LoginRegister/js/main.js' %}"></script>

</body>
</html>

{% comment %} 
<html>
	<body>
		<form method="POST">
			{% csrf_token %}
			{{ form }}
			<button Value="Submit" type="Submit"> Submit </button>
		</form>
	</body>
</html> {% endcomment %}