e-pustakshala-main/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('Cart/', views.CartView , name="CartView"),
    path('Cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('Cart/Remove/<int:id>', views.remove_from_cart , name="remove_from_cart"),
    path('Cart/Delete/<int:id>', views.decreaseCart , name="decreaseCart"),
    path('Cart/Checkout', views.Checkout , name="Checkout"),
    path('Cart/invoice', views.invoice , name="invoice"),
]

e-pustakshala-main/MainIndex/urls.py
from django.urls import path, include
from MainIndex.views import *

app_name = 'MainIndex'

urlpatterns = [
    path('',views.index, name="index"),
    path('contact/', views.contact , name="contact"),
    path('Category/<int:id>', views.CategoryView , name="CategoryView"),
    path('Publication/<int:id>', views.PublicationView , name="PublicationView"),
    path('Author/<int:id>', views.AuthorView , name="AuthorView"),
    path('Search/', views.SearchView , name="SearchView"),
    path('Details/<int:id>', views.DetailsView , name="DetailsView"),
    path('Contact',views.contact,name="contact"),
    path('About' , views.About , name="About"),
    path('gameofthrones', views.got , name="got"),
    path('HarryPotter' , views.hp , name="hp"),
    path('Twilight' , views.tw , name="tw"),
    path('AllBooks' , views.allBooks , name="allBooks"),
    

]

e-pustakshala-main/Pustakshala/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import smtplib

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Registration.urls')),
    path('', include('MainIndex.urls')),
    path('', include('Cart.urls')),

]
 
urlpatterns +=staticfiles_urlpatterns()

e-pustakshala-main/Cart/models.py
from django.db import models
from Registration.models import Customer
from MainIndex.models import Book





# Cart Model
class Cart(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, default=15)
    item = models.ForeignKey(Book, on_delete=models.CASCADE, default=1)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f'{self.quantity} of {self.item.BookName }'

    def get_total(self):
        total = self.item.BookPrice * self.quantity
        floattotal = float("{0:.2f}".format(total))
        return floattotal

    def cart_delete(self):
        self.delete()
    
    

# Order Model
class Order(models.Model):
    orderitems  = models.ManyToManyField(Cart)
    user = models.ForeignKey(Customer, on_delete=models.CASCADE , default=12)
    # alreadyregistered = models.IntegerField(default=0)
    def __str__(self):
        return self.user.CustomerName
    
    def get_totals(self):
        total =0
        for order_item in self.orderitems.all():
            total += order_item.get_total()
        return total

e-pustakshala-main/Cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic

from Registration.models import Customer

from .models import *
import os
import sys
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
import datetime
import time
import smtplib
import pymysql.cursors
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from datetime import date
# Create your views here.

Customer_session_nm = None
Customer_session_id = None
order = None
carts = None
  
def CartView(request):
    Customer_session_nm = None
    Customer_session_id = None
    order =None
    carts = None
    Books = Book.objects.all()
    if request.session.has_key('name'):
        Customer_session_nm=request.session['name']
    if request.session.has_key('id'):
            Customer_session_id=request.session['id']
            user = Customer_session_id
    bname=request.GET.get('Bookname')
    if bname!='' and bname is not None:
        Books=Books.filter(BookName__icontains= bname)
        if request.session.has_key('name'):
            Customer_session_nm=request.session['name']
            return render(request,'ShowSearch.html',{'Books':Books, 'Customer_session_nm':Customer_session_nm , 'name':Customer.objects.get(id=user).CustomerName.capitalize()})
        else:
            return render(request,'ShowSearch.html',{'Books':Books})
    if request.session.has_key('name'):
        Customer_session_nm=request.session['name']
        Customer_session_id = None
        if request.session.has_key('id'):
            Customer_session_id=request.session['id']
        user = Customer_session_id

        carts = Cart.objects.filter(user=user)
        orders = Order.objects.filter(user=user)
        if carts.exists():
            print("if")
            if orders.exists():
                print("if if ")
                order = orders[0]
                return render(request, 'cart.html', {'carts': carts, 'order': order , 'Customer_session_nm':Customer_session_nm , 'name':Customer.objects.get(id=user).CustomerName.capitalize() })
            else:
                return render(request,'cart.html' ,{ 'carts': carts, 'order': order , 'Customer_session_nm':Customer_session_nm  , 'name':Customer.objects.get(id=user).CustomerName.capitalize()} )
                # messages.warning(request, "You do not have any item in your Cart")

            
        else:
            print('else')
            # messages.warning(request, "You do not have any item in your Cart")
            return render(request,'cart.html' ,{ 'carts': carts, 'order': order ,'Customer_session_nm':Customer_session_nm , 'name':Customer.objects.get(id=user).CustomerName.capitalize()} )
    else:
        return redirect("Registration:Login")



def add_to_cart(request, id):
    
    # Customerfds = Customer.objects.get(id=15)
    Customer_session_nm = None
    Customer_session_id = None
    if request.session.has_key('name'):
        if request.session.has_key('id'):
            Customer_session_id=request.session['id']
        userid = Customer_session_id
        item = get_object_or_404(Book, id=id)
        Customer_name=Customer.objects.get(id=userid)
        order_item, created = Cart.objects.get_or_create(
            item=item,
            user=Customer_name
        )
        order_qs = Order.objects.filter(user=userid)
        if order_qs.exists():
            order = order_qs[0]
            print('order if')
            # check if the order item is in the order
            if order.orderitems.filter(item__id=item.id).exists():
                print('order if if')
                order_item.quantity += 1
                updatestock(userid)
                order_item.save()
                # messages.info(request, f"{item.BookName} quantity has updated.")
                return redirect("Cart:CartView")
            else:
                
                order.orderitems.add(order_item)
                updatestock(userid)
                # messages.info(request, f"{item.BookName} has added to your cart.")
                return redirect("Cart:CartView")
        else:
            order = Order.objects.create(user=Customer_name)
            order.orderitems.add(order_item)
            # messages.info(request, f"{item.BookName} has added to your cart.")
            return redirect("Cart:CartView")
    else:
        return redirect("Registration:Login")

def remove_from_cart(request, id):
    Customer_session_nm = None
    Customer_session_id = None
    if request.session.has_key('id'):
        Customer_session_id=request.session['id']
    userid = Customer_session_id
    Customer_name=Customer.objects.get(id=userid)
    item = get_object_or_404(Book, id=id)
    cart_qs = Cart.objects.filter(user=Customer_name , item=item)

    
    
    
    if cart_qs.exists():
        cart = cart_qs[0]
        # Checking the cart quantity
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart_qs.delete()
    order_qs = Order.objects.filter(
        user=Customer_name)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderitems.filter(item__id=item.id).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=Customer_name,
            )[0]
            order_item.delete()
            # messages.warning(request, "This item was removed from your cart.")
            return redirect("Cart:CartView")
        else:
            # messages.warning(request, "This item was not in your cart")
            return redirect("Cart:CartView")
    else:
        # messages.warning(request, "You do not have an active order")
        return redirect("MainIndex:index")


def decreaseCart(request,id):
    Customer_session_nm = None
    Customer_session_id = None
    if request.session.has_key('id'):
        Customer_session_id=request.session['id']
    userid = Customer_session_id
    Customer_name=Customer.objects.get(id=userid)
    item = get_object_or_404(Book, id=id)
    order_qs = Order.objects.filter(
        user=Customer_name
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderitems.filter(item__id=item.id).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=Customer_name
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                updatestockdes(userid)
                order_item.save()
            else:
                order.orderitems.remove(order_item)
                updatestockdes(userid)
                order_item.delete()
                # messages.warning(request, f"{item.BookName} has removed from your cart.")
            # messages.info(request, f"{item.BookName} quantity has updated.")
            return redirect("Cart:CartView")
        else:
            # messages.info(request, f"{item.BookName} quantity has updated.")
            return redirect("Cart:CartView")
    else:
        # messages.info(request, "You do not have an active order")
        return redirect("MainIndex:index")


def Checkout(request):
    Customer_session_nm = None
    Customer_session_id = None
    if request.session.has_key('name'):
        Customer_session_nm=request.session['name']
    else:
        return redirect('MainIndex:index')
    if request.session.has_key('id'):
        Customer_session_id=request.session['id']
        user = Customer_session_id
    if request.session.has_key('name'):
        Customer_session_nm=request.session['name']
    if request.session.has_key('id'):
            Customer_session_id=request.session['id']
            print(Customer_session_id)
    user = Customer_session_id
    userid = Customer_session_id 
    carts = Cart.objects.filter(user=user)
    orders = Order.objects.filter(user=user)
    Customer_obj = Customer.objects.get(id=userid)
    if carts.exists():
        print("if")
        if orders.exists():
            print("if if ")
            order = orders[0]
        else:
            order = None
            carts = None
            return redirect("MainIndex:index")
    else:
        order = None
        carts = None
        return redirect("MainIndex:index")
    if request.method=='POST':
        firstname=request.POST.get('Billingfirst','')
        lastname=request.POST.get('Billinglast','')
        address = request.POST.get('firstaddress','')
        address2 = request.POST.get('secondaddress','')
        pincode = request.POST.get('pincode','')
        state = request.POST.get('state','')
        city = request.POST.get('city','')
        Cus = Customer.objects.get(id=user)
        Cus.CustomerAddress = address
        Cus.CustomerAddress2 = address2
        Cus.CustomerPincode  = pincode
        Cus.BillingFirstName = firstname
        Cus.BillingLastName = lastname
        Cus.CustomerState = state
        Cus.CustomerCity = city
        Cus.save()
        createpdf(userid)
        # updatestock(userid)
        try:
            sendbill(Cus.CustomerEmail)
        except:
            print('error sending mail')
        return redirect("Cart:invoice")

    
    Detailsbook=Book.objects.all()
    bname=request.GET.get('Bookname')
    if bname!='' and bname is not None:
        searchBooks=Detailsbook.filter(BookName__icontains= bname)
        if request.session.has_key('name'):
            Customer_session_nm=request.session['name']
            return render(request,'ShowSearch.html',{'user':Customer_obj,'Books':searchBooks, 'Customer_session_nm':Customer_session_nm , 'order':order , 'carts':carts , 'name':Customer.objects.get(id=user).CustomerName.capitalize()})
        else:
            return render(request,'ShowSearch.html',{'Books':searchBooks})

e-pustakshala-main/templates/ShowAuthor.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
</head>
<body class="animsition">
	{% block body %}
	
		<!-- Title Page -->
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url('/static/images/5.jpg');">
		<h2 class="l-text2 t-center">
		{% for book in Name %}
			{{ book }}
		{% endfor %}
		</h2>
	</section>
	
	 <div class="container">
			<div class="row">
			{% if Books %}
			{% for Book in Books %}
		<div class="col-sm-10 col-md-3 col-lg-3 m-b-60 m-t-60">
			{% comment %} <div class="item p-l-15 p-r-15"> {% endcomment %}
						
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative">
								<img src="{{ Book.BookImage }}" alt="IMG-PRODUCT" height="369" ></a>

	
								<div class="block2-overlay trans-0-4">


									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{% url 'MainIndex:DetailsView' Book.id  %}"><span class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Details
										</span></a>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'MainIndex:DetailsView' Book.id %}" class="block2-name dis-block s-text3 p-b-5">
									{{ Book.BookName }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									<strong>₹.</strong>{{ Book.BookPrice }}
			
								</span>
							</div>
						</div>
					</div>

		{% endfor %}
		{% else %}
			<div style="margin-left:30%; margin-top:5%; margin-bottom:5%">
				<img src="{% static 'images/notfound.png'%}" width="50%">
			</div>
		{% endif %}
		</div>
		</div>
    {% endblock %}
</body>
</html>

e-pustakshala-main/templates/ShowBooks.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
</head>
<body class="animsition">
	{% block body %}
	
		<!-- Title Page -->
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url('/static/images/2.jpg');">
		<h2 class="l-text2 t-center">
		{% for book in Name %}
			{{ book }}
		{% endfor %}
		</h2>
	</section>
	
	 <div class="container">
			<div class="row">
			{% if Books %}
			{% for Book in Books %}
		
		 <div class="col-sm-10 col-md-3 col-lg-3 m-b-60 m-t-60">
			{% comment %} <div class="item p-l-15 p-r-15"> {% endcomment %}
						
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative">
								<img src="{{ Book.BookImage }}" alt="IMG-PRODUCT" height="369" ></a>

	
								<div class="block2-overlay trans-0-4">


									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{% url 'MainIndex:DetailsView' Book.id  %}"><span class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Details
										</span></a>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'MainIndex:DetailsView' Book.id %}" class="block2-name dis-block s-text3 p-b-5">
									{{ Book.BookName }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									<strong>₹.</strong>{{ Book.BookPrice }}
			
								</span>
							</div>
						</div>
					</div>

		{% endfor %}
		{% else %}
			<div style="margin-left:30%; margin-top:5%; margin-bottom:5%">
				<img src="{% static 'images/notfound.png'%}" width="50%">
			</div>
		{% endif %}
		</div>
		</div>
    {% endblock %}
</body>
</html>

e-pustakshala-main/templates/ShowSearch.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
	
</head>
<body class="animsition">
	{% block body %}
	
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m m-b-30" style="background-image: url('/static/images/3.jpg');">
		<h2 class="l-text2 t-center">
			Searches
		</h2>
	</section>

		<div class="container">
			<div class="row">
			{% if Books %}
			{% for Book in Books %}
            <div class="col-sm-10 col-md-3 col-lg-3 m-b-60">
			{% comment %} <div class="item p-l-15 p-r-15"> {% endcomment %}
						
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative">
								<img src="{{ Book.BookImage }}" alt="IMG-PRODUCT" height="369" ></a>

	
								<div class="block2-overlay trans-0-4">


									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{% url 'MainIndex:DetailsView' Book.id  %}"><span class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Details
										</span></a>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'MainIndex:index' %}" class="block2-name dis-block s-text3 p-b-5">
									{{ Book.BookName }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									<strong>₹.</strong>{{ Book.BookPrice }}
			
								</span>
							</div>
						</div>
					</div>
			{% endfor %}
			{% else %}
			<div style="margin-left:30%; margin-top:5%; margin-bottom:5%">
				<img src="{% static 'images/notfound.png'%}" width="50%">
			</div>
		{% endif %}
			</div>
		</div>

	{% endblock %}
</body>
</html>

e-pustakshala-main/templates/allBooks.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
	
</head>
<body class="animsition">
	{% block body %}
	 <div class="container">
			<div class="row">
			{% for cat in  category %}
				<span class="fs" style="width:100%; border-bottom:3px solid #00CCC2; margin-bottom:50px; margin-left:10px; font-family:'Julius Sans One',sans-serif; padding-bottom:8px; font-size: 40px; font-weight:700; color: #00ACC1;" >{{ cat.CategoryName }}</span>
			{% for Book in cat.get_products %}
				            <div class="col-sm-10 col-md-3 col-lg-3 m-b-60">
			{% comment %} <div class="item p-l-15 p-r-15"> {% endcomment %}
						
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative">
								<img src="{{ Book.BookImage }}" alt="IMG-PRODUCT" height="369" ></a>

	
								<div class="block2-overlay trans-0-4">


									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{% url 'MainIndex:DetailsView' Book.id  %}"><span class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Details
										</span></a>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'MainIndex:DetailsView' Book.id %}" class="block2-name dis-block s-text3 p-b-5">
									{{ Book.BookName }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									<strong>₹.</strong>{{ Book.BookPrice }}
			
								</span>
							</div>
						</div>
					</div>
		{% endfor %}
		{% endfor %}
		</div>
		</div>
	{% endblock %}
</body>
</html>

e-pustakshala-main/templates/index.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
	
</head>
<body class="animsition">
	{% block body %}
	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">
			<div class="item-slick1 item3-slick1" style="background-image: url(/static/images/poster2.jpg);">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rotateInDownLeft">
							Explore Exciting series
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="rotateInUpRight">
							<div align="center"><img src="{% static 'images/gotlogo.png' %}" width="50%"></div>
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="rotateIn">
							<!-- Button -->
							<a href="{% url 'MainIndex:got'%}" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								view Books
							</a>
						</div>
					</div>
				</div>
				<div class="item-slick1 item1-slick1" style="background-image: url('/static/images/hpposter.jpg');">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-100">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="fadeInDown">
							Explore Exciting series
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-15" data-appear="fadeInUp">
							<img src="{% static 'images/hplogo.png' %}">
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
							<!-- Button -->
							<a href="{% url 'MainIndex:hp'%}" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								View Books
							</a>
						</div>
					</div>
				</div>

				<div class="item-slick1 item2-slick1" style="background-image: url('/static/images/twilightposter.jpg');">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-220 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rollIn">
							Explore Exciting series
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37 p-l-170" data-appear="lightSpeedIn">
							<img src="{% static 'images/twilightlogo.png' %}" width="80%">
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">
							<!-- Button -->
							<a href="{% url 'MainIndex:tw'%}" class="flex-c-m size2 bo-rad-23 s-text2 text-light bg-dark hov1 trans-0-4">
								View Books
							</a>
						</div>
					</div>
				</div>

				

			</div>
		</div>
	</section>

	<!-- Banner -->
	<section class="banner bgwhite p-t-40 p-b-40 m-t-60">
		<div class="container">
		<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Categories
				</h3>
			</div>
			<div class="row">
			{% for Category  in Categorys %}
			
				<div class="col-sm-10 col-md-3 col-lg-3">
					<!-- block1 -->
					<div class="block1 hov-img-zoom pos-relative m-b-30">
						<img src="{{ Category.CategoryImage }}" alt="IMG-BENNER" style="height:410px; overflow:hidden">

						<div class="block1-wrapbtn w-size2">
							<!-- Button -->
							<a href="{% url 'MainIndex:CategoryView' Category.id %}" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
								{{ Category.CategoryName }}
							</a>
						</div>
					</div>
				</div>
			{% endfor %}
			</div>
		</div>
	</section>

	<!-- New Product -->
	<section class="newproduct bgwhite p-t-45 p-b-50">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Our Best Sellers
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

					{% for Book in Books %}
					{% if  forloop.counter <= 8 %}
					<div class="item-slick2 p-l-15 p-r-15">
						
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative">
								<img src="{{ Book.BookImage }}" alt="IMG-PRODUCT"></a>

	
								<div class="block2-overlay trans-0-4">
		
									{% comment %} <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
										<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
										<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
									</a> {% endcomment %}


									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{% url 'MainIndex:DetailsView' Book.id  %}"><span class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Details
										</span></a>
										
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'MainIndex:DetailsView' Book.id	 %}" class="block2-name dis-block s-text3 p-b-5">
									{{ Book.BookName }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									<strong>₹.</strong>{{ Book.BookPrice }}
			
								</span>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
			</div>			
		</div>
	</section>
	
	<!-- Blog -->
	<section class="blog bgwhite p-t-70 p-b-65">
			<div class="container">
				<div class="sec-title p-b-52">
					<h3 class="m-text5 t-center">
							Best Publications
					</h3>
				</div>
				<div class="row">
				{% for Publication in Publications %}
				{% if  forloop.counter <= 8 %}
					<div class="col-sm-14 col-md-3 p-b-30">
						<!-- Block3 -->
						<div class="block3">
							<a href="{% url 'MainIndex:PublicationView' Publication.id %}" class="block3-img dis-block hov-img-zoom">
								<img src="{{ Publication.PublicationImage }}" alt="IMG-BLOG" style="height:103px; width:160px;">
							</a>

							<div class="block3-txt p-t-10">
								<h4 class="p-b-7">
									<a href="{% url 'MainIndex:PublicationView' Publication.id %}" class="m-text11">
										{{ Publication.PublicationName }}
									</a>
								</h4>
								<p class="s-text8 p-t-10 overflow-hidden">
									{{ Publication.PublicationDesc }}
								</p>
							</div>
						</div>
					</div>
					{% endif %}
				{% endfor %}
				</div>
			</div>
					<div class="sec-title p-l-15 p-r-15">
			<h3 class="m-text5 t-center">
				Best Selling Author
			</h3>
		</div>
		</section>
	
	<!-- Instagram -->
	<section class="instagram">
		<div class="flex-w">
		<!-- Block4 -->
				{% for Author in Authors %}
				{% if  forloop.counter <= 5 %}
				<div class="block4 wrap-pic-w">
					<img src="{{ Author.AuthorImage}}" alt="authorimage" height="318px">

					<a href="{% url 'MainIndex:AuthorView' Author.id %}" class="block4-overlay sizefull ab-t-l trans-0-4">
						<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
							<p class="s-text10 m-b-15 h-size1 of-hidden">
							</p>

							<span class="s-text9 p-t-30">
								{{ Author.AuthorName }}
							</span><br><br>
							<span class="s-text11">
								{{ Author.AuthorDesc }}
							</span>
						</div>
					</a>
				</div>
				{% endif%}
				{% endfor %}
		</div>
	</section>
		


{% comment %} login frame modal {% endcomment %}


{% endblock %}
</body>
</html>